name: Push

on: [pull_request, push]

jobs:
  remote-echidna:
    uses: aviggiano/remote-echidna/.github/workflows/remote-echidna.yml@main
    with:
      project: "re2"
      project_git_url: "https://github.com/${{github.repository}}.git"
      project_git_checkout: ${{ github.head_ref || github.ref_name }}
      s3_bucket: ${{ secrets.REMOTE_ECHIDNA_S3_BUCKET }}
      ec2_instance_key_name: ${{ secrets.EC2_INSTANCE_KEY_NAME }}
      run_tests_cmd: "echidna-test contracts/Contract.sol --contract Contract --config config.yaml || true"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    name: Run remote-echidna

