name: Push

on: [pull_request, push]

jobs:
  provision:
    name: Provision resources
    uses: aviggiano/remote-echidna/.github/workflows/remote-echidna.yml@v1
    with:
      project: "demo"
      project_git_url: "https://github.com/aviggiano/yield-contracts.git"
      project_git_checkout: crytic-properties
      run_tests_cmd: "echidna-test test/invariants/STETHVaultInvariants.sol --contract STETHVaultInvariants --config test/invariants/config-assertion.yaml --test-limit 1000000"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      REMOTE_ECHIDNA_S3_BUCKET: ${{ secrets.REMOTE_ECHIDNA_S3_BUCKET }}
      REMOTE_ECHIDNA_EC2_INSTANCE_KEY_NAME: ${{ secrets.REMOTE_ECHIDNA_EC2_INSTANCE_KEY_NAME }}