name: Push

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  remote-echidna:
    name: Remote echidna
    permissions:
      pull-requests: write
    uses: aviggiano/remote-echidna/.github/workflows/remote-echidna.yml@v2
    with:
      project: "demo"
      project_git_url: "https://github.com/aviggiano/yield-contracts.git"
      project_git_checkout: "feat/add-more-properties"
      run_tests_cmd: "yarn && echidna-test test/invariants/STETHVaultUnitTests.sol --contract STETHVaultUnitTests --config test/invariants/config-unit-tests.yaml --test-limit 1000"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      REMOTE_ECHIDNA_S3_BUCKET: ${{ secrets.REMOTE_ECHIDNA_S3_BUCKET }}
      REMOTE_ECHIDNA_EC2_INSTANCE_KEY_NAME: ${{ secrets.REMOTE_ECHIDNA_EC2_INSTANCE_KEY_NAME }}